import type { CourseRecord, NavItem, StudentProfile } from "@/features/home/types";

export const navigationItems: NavItem[] = [
  { label: "estudiante",iconName:"twoPersons", active: true },
  { label: "profesor",iconName:"professor", },
  { label: "class",iconName:"class", },
  { label: "plan",iconName:"curriculum", },
  { label: "horario",iconName:"schedule", },
  { label: "admin",iconName:"admin", },
];

export const studentProfile: StudentProfile = {
  program: "Ingenieria en informatica y negocios digitales",
  planLabel: "TIND",
  name: "Ryan Rafael Garcia",
  status: "activo",
  progressValue: "74",
  progressSuffix: "%",
  progressLabel: "1/2",
  contactActions: ["school", "mail", "chat"],
  summaryItems: [
    { label: "id", value: "00246042" },
    { label: "semester", value: "6" },
    { label: "requisitos", value: "1/2" },
  ],
};

export const filterTags = ["cruzado", "aprobado", "pendiente", "posibles"];

export const tableHeaders = [
  "code",
  "number",
  "titulo",
  "calificacion",
  "registrando",
  "semester registrado",
  "semester recomendado",
  "credito",
  "hora",
  "prerequisito",
  "materia posterior",
] as const;

export const columnWidths = [
  "w-16",
  "w-24",
  "w-64",
  "w-28",
  "w-32",
  "w-44",
  "w-48",
  "w-20",
  "w-16",
  "w-32",
  "w-40",
];

export const records: CourseRecord[] = [
  {
    code: "2405",
    number: "CMP2405",
    title: "Arquitectura de computadoras",
    grade: "9.0",
    registered: "2026/ene-jun",
    semesterRegistered: "2",
    semesterRecommended: "4",
    credit: "7",
    hours: "4.5",
    prerequisite: "Info de comp.",
    nextCourse: "Teorica de hardware",
  },
  {
    code: "2408",
    number: "CMP2408",
    title: "Bases de datos",
    grade: "8.7",
    registered: "2026/ene-jun",
    semesterRegistered: "3",
    semesterRecommended: "4",
    credit: "6",
    hours: "4.0",
    prerequisite: "Prog. orientada",
    nextCourse: "Mineria de datos",
  },
  {
    code: "2410",
    number: "CMP2410",
    title: "Redes y conectividad",
    grade: "7.8",
    registered: "2026/ene-jun",
    semesterRegistered: "4",
    semesterRecommended: "5",
    credit: "6",
    hours: "4.0",
    prerequisite: "Sistemas dig.",
    nextCourse: "Seguridad de red",
  },
  {
    code: "2414",
    number: "CMP2414",
    title: "Desarrollo web",
    grade: "10.0",
    registered: "2026/ene-jun",
    semesterRegistered: "4",
    semesterRecommended: "5",
    credit: "7",
    hours: "4.5",
    prerequisite: "Fund. de prog.",
    nextCourse: "Aplicaciones full stack",
  },
  {
    code: "2421",
    number: "CMP2421",
    title: "Analisis de algoritmos",
    grade: "8.3",
    registered: "2026/ene-jun",
    semesterRegistered: "5",
    semesterRecommended: "6",
    credit: "6",
    hours: "4.0",
    prerequisite: "Matematica discreta",
    nextCourse: "Optimizacion",
  },
  {
    code: "2425",
    number: "CMP2425",
    title: "Ingenieria de software",
    grade: "9.5",
    registered: "2026/ene-jun",
    semesterRegistered: "5",
    semesterRecommended: "6",
    credit: "7",
    hours: "4.5",
    prerequisite: "Diseno de sist.",
    nextCourse: "Arquitectura empresarial",
  },
  {
    code: "2430",
    number: "CMP2430",
    title: "Inteligencia de negocios",
    grade: "Pend.",
    registered: "2026/ago-dic",
    semesterRegistered: "6",
    semesterRecommended: "7",
    credit: "6",
    hours: "4.0",
    prerequisite: "Bases de datos",
    nextCourse: "Analitica avanzada",
  },
  {
    code: "2433",
    number: "CMP2433",
    title: "UX para productos digitales",
    grade: "Pend.",
    registered: "2026/ago-dic",
    semesterRegistered: "6",
    semesterRecommended: "7",
    credit: "5",
    hours: "3.5",
    prerequisite: "Desarrollo web",
    nextCourse: "Diseno de servicios",
  },
];
