export const STUDENT_AVATAR_COLOR_PALETTE = [
  "--ADM-strong",
  "--CMP-strong",
  "--CUL-strong",
  "--SOC-strong",
  "--IELC-strong",
  "--EMP-strong",
  "--FIS-strong",
  "--HUM-strong",
  "--IIND-strong",
  "--CON-strong",
  "--INT-strong",
  "--LDR-strong",
  "--MAT-strong",
  "--SIS-strong",
] as const;
